name: Checks

on: [ push ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os}}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: poetry install --no-root
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Create .env
        run: cp ./watchtower/.env.sample ./watchtower/.env
      - name: Run Black
        run: poetry run black
      - name: Run flake8
        run: poetry run flake8
      - name: Run isort
        run: poetry run isort . --check
      - name: Run Mypy
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-watchtower
          fail_ci_if_error: true
      - name: Clean up
        run: rm coverage.xml
