name: Leopold

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  fc660m_bt_available:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os}}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: poetry install --no-root
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run
        run: poetry run python -m watchtower.leopold.main
        env:
          NAVER_MAIL_USER: ${{ secrets.NAVER_MAIL_USER }}
          NAVER_MAIL_PASSWORD: ${{ secrets.NAVER_MAIL_PASSWORD }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
